use std::collections::HashMap;



#[repr(u32)]
#[derive(Hash, Eq, PartialEq, Clone, Copy)]
pub enum Canned {
    Arrived = 1,
    ContinueOnTheRamp = 2,
    ContinueStraight = 3,
    DataLost = 4,
    DestinationOnLeft = 5,
    DestinationOnRight = 6,
    DestinationWillBeOnLeft = 7,
    DestinationWillBeOnRight = 8,
    EnterTheRoundabout = 9,
    ExitTheRoundabout = 10,
    GenericContinue = 11,
    GpsLost = 12,
    HeadEast = 13,
    HeadNorth = 14,
    HeadNortheast = 15,
    HeadNorthwest = 16,
    HeadSouth = 17,
    HeadSoutheast = 18,
    HeadSouthwest = 19,
    HeadWest = 20,
    In1000Feet = 21,
    In100Feet = 22,
    In100Meters = 23,
    In100Yards = 24,
    In150Feet = 25,
    In150Meters = 26,
    In150Yards = 27,
    In1AndAHalfKilometers = 28,
    In1AndAHalfMiles = 29,
    In1Kilometer = 30,
    In1Mile = 31,
    In200Feet = 32,
    In200Meters = 33,
    In200Yards = 34,
    In2Kilometers = 35,
    In2Miles = 36,
    In300Feet = 37,
    In300Meters = 38,
    In300Yards = 39,
    In3Kilometers = 40,
    In3Miles = 41,
    In400Feet = 42,
    In400Meters = 43,
    In400Yards = 44,
    In500Feet = 45,
    In500Meters = 46,
    In50Feet = 47,
    In50Meters = 48,
    In50Yards = 49,
    In600Feet = 50,
    In600Meters = 51,
    In800Feet = 52,
    In800Meters = 53,
    InAHalfMile = 54,
    InAQuarterMile = 55,
    InThreeQuartersOfAMile = 56,
    KeepLeftAtTheFork = 57,
    KeepRightAtTheFork = 58,
    MakeAUturn = 59,
    NavigationResumed = 60,
    PleaseDescribeProblem = 61,
    Roundabout1stExit = 62,
    RoundaboutExitIntoTheRamp = 63,
    RoundaboutTake2ndExit = 64,
    RoundaboutTake3rdExit = 65,
    RoundaboutTake4thExit = 66,
    RoundaboutTake5thExit = 67,
    SharpLeft = 68,
    SharpRight = 69,
    SlightLeft = 70,
    SlightLeftOntoTheRamp = 71,
    SlightRight = 72,
    SlightRightOntoRamp = 73,
    TakeTheInterchange = 74,
    TakeTheInterchangeOnTheLeft = 75,
    TakeTheExit = 76,
    TakeTheExitOnTheLeft = 77,
    TakeTheExitOnTheRight = 78,
    TakeTheFerry = 79,
    TakeTheInterchangeOnTheRight = 80,
    TakeTheRamp = 81,
    TakeTheTrain = 82,
    Then = 83,
    TurnLeft = 84,
    TurnLeftOntoRamp = 85,
    TurnRight = 86,
    TurnRightOntoTheRamp = 87,
    WillArrive = 88,
}

pub fn default_canned_message(c: Canned) -> String {
    match c {
        Canned::Arrived => "目的地に到着しました、お疲れさまでした。",
        Canned::ContinueOnTheRamp => "分岐です。",
        Canned::ContinueStraight => "直進です。",
        Canned::DataLost => "データ接続が失われました。",
        Canned::DestinationOnLeft => "目的地は左側です、お疲れさまでした。",
        Canned::DestinationOnRight => "目的地は右側です、お疲れさまでした。",
        Canned::DestinationWillBeOnLeft => "目的地は左側です。",
        Canned::DestinationWillBeOnRight => "目的地は右側です。",
        Canned::EnterTheRoundabout => "ロータリー入口です。",
        Canned::ExitTheRoundabout => "ロータリー出口です。",
        Canned::GenericContinue => "しばらく道なりです。",
        Canned::GpsLost => "GPS信号が失われました。",
        Canned::HeadEast => "東に進みます。",
        Canned::HeadNorth => "北に進みます。",
        Canned::HeadNortheast => "北東に進みます。",
        Canned::HeadNorthwest => "北西に進みます。",
        Canned::HeadSouth => "南に進みます。",
        Canned::HeadSoutheast => "南東に進みます。",
        Canned::HeadSouthwest => "南西に進みます。",
        Canned::HeadWest => "西に進みます。",
        Canned::In1000Feet => "およそ1000フィート先。",
        Canned::In100Feet => "およそ100フィート先。",
        Canned::In100Meters => "およそ100メートル先。",
        Canned::In100Yards => "およそ100ヤード先。",
        Canned::In150Feet => "およそ150フィート先。",
        Canned::In150Meters => "およそ150メートル先。",
        Canned::In150Yards => "およそ150ヤード先。",
        Canned::In1AndAHalfKilometers => "およそ1.5キロ先。",
        Canned::In1AndAHalfMiles => "およそ1.5マイル先。",
        Canned::In1Kilometer => "およそ1キロ先。",
        Canned::In1Mile => "およそ1マイル先。",
        Canned::In200Feet => "およそ200フィート先。",
        Canned::In200Meters => "およそ200メートル先。",
        Canned::In200Yards => "およそ200ヤード先。",
        Canned::In2Kilometers => "およそ2キロ先。",
        Canned::In2Miles => "およそ2マイル先。",
        Canned::In300Feet => "およそ300フィート先。",
        Canned::In300Meters => "およそ300メートル先。",
        Canned::In300Yards => "およそ300ヤード先。",
        Canned::In3Kilometers => "およそ3キロ先。",
        Canned::In3Miles => "およそ3マイル先。",
        Canned::In400Feet => "およそ400フィート先。",
        Canned::In400Meters => "およそ400メートル先。",
        Canned::In400Yards => "およそ400ヤード先。",
        Canned::In500Feet => "およそ500フィート先。",
        Canned::In500Meters => "およそ500メートル先。",
        Canned::In50Feet => "およそ50フィート先。",
        Canned::In50Meters => "およそ50メートル先。",
        Canned::In50Yards => "およそ50ヤード先。",
        Canned::In600Feet => "およそ600フィート先。",
        Canned::In600Meters => "およそ600メートル先。",
        Canned::In800Feet => "およそ800フィート先。",
        Canned::In800Meters => "およそ800メートル先。",
        Canned::InAHalfMile => "およそ0.5マイル先。",
        Canned::InAQuarterMile => "およそ0.25マイル先。",
        Canned::InThreeQuartersOfAMile => "およそ0.75マイル先。",
        Canned::KeepLeftAtTheFork => "分岐を左方向です。",
        Canned::KeepRightAtTheFork => "分岐を右方向です。",
        Canned::MakeAUturn => "Uターンです。",
        Canned::NavigationResumed => "ナビを再開します。",
        Canned::PleaseDescribeProblem => "問題の内容をお話ください。",
        Canned::Roundabout1stExit => "ロータリー1番目の出口です。",
        Canned::RoundaboutExitIntoTheRamp => "ロータリーからランプに進みます。",
        Canned::RoundaboutTake2ndExit => "ロータリー2番目の出口です。",
        Canned::RoundaboutTake3rdExit => "ロータリー3番目の出口です。",
        Canned::RoundaboutTake4thExit => "ロータリー4番目の出口です。",
        Canned::RoundaboutTake5thExit => "ロータリー5番目の出口です。",
        Canned::SharpLeft => "大きく左方向です。",
        Canned::SharpRight => "大きく右方向です。",
        Canned::SlightLeft => "斜め左方向です。",
        Canned::SlightLeftOntoTheRamp => "斜め左方向、入口です。",
        Canned::SlightRight => "斜め右方向です。",
        Canned::SlightRightOntoRamp => "斜め右方向、入口です。",
        Canned::TakeTheInterchange => "ジャンクションです。",
        Canned::TakeTheInterchangeOnTheLeft => "左方向、ジャンクションです。",
        Canned::TakeTheExit => "出口です。",
        Canned::TakeTheExitOnTheLeft => "左方向、出口です。",
        Canned::TakeTheExitOnTheRight => "右方向、出口です。",
        Canned::TakeTheFerry => "フェリーに乗ります。",
        Canned::TakeTheInterchangeOnTheRight => "右方向、ジャンクションです。",
        Canned::TakeTheRamp => "入口です。",
        Canned::TakeTheTrain => "電車に乗ります。",
        Canned::Then => "その先。",
        Canned::TurnLeft => "左方向です。",
        Canned::TurnLeftOntoRamp => "左方向、入口です。",
        Canned::TurnRight => "右方向です。",
        Canned::TurnRightOntoTheRamp => "右方向、入口です。",
        Canned::WillArrive => "目的地です。",
    }.to_string()
}

impl Canned {
    pub const ALL: &'static [Canned] = &[
        Canned::Arrived, Canned::ContinueOnTheRamp, Canned::ContinueStraight, Canned::DataLost,
        Canned::DestinationOnLeft, Canned::DestinationOnRight, Canned::DestinationWillBeOnLeft,
        Canned::DestinationWillBeOnRight, Canned::EnterTheRoundabout, Canned::ExitTheRoundabout,
        Canned::GenericContinue, Canned::GpsLost, Canned::HeadEast, Canned::HeadNorth,
        Canned::HeadNortheast, Canned::HeadNorthwest, Canned::HeadSouth, Canned::HeadSoutheast,
        Canned::HeadSouthwest, Canned::HeadWest, Canned::In1000Feet, Canned::In100Feet,
        Canned::In100Meters, Canned::In100Yards, Canned::In150Feet, Canned::In150Meters,
        Canned::In150Yards, Canned::In1AndAHalfKilometers, Canned::In1AndAHalfMiles,
        Canned::In1Kilometer, Canned::In1Mile, Canned::In200Feet, Canned::In200Meters,
        Canned::In200Yards, Canned::In2Kilometers, Canned::In2Miles, Canned::In300Feet,
        Canned::In300Meters, Canned::In300Yards, Canned::In3Kilometers, Canned::In3Miles,
        Canned::In400Feet, Canned::In400Meters, Canned::In400Yards, Canned::In500Feet,
        Canned::In500Meters, Canned::In50Feet, Canned::In50Meters, Canned::In50Yards,
        Canned::In600Feet, Canned::In600Meters, Canned::In800Feet, Canned::In800Meters,
        Canned::InAHalfMile, Canned::InAQuarterMile, Canned::InThreeQuartersOfAMile,
        Canned::KeepLeftAtTheFork, Canned::KeepRightAtTheFork, Canned::MakeAUturn,
        Canned::NavigationResumed, Canned::PleaseDescribeProblem, Canned::Roundabout1stExit,
        Canned::RoundaboutExitIntoTheRamp, Canned::RoundaboutTake2ndExit, Canned::RoundaboutTake3rdExit,
        Canned::RoundaboutTake4thExit, Canned::RoundaboutTake5thExit, Canned::SharpLeft,
        Canned::SharpRight, Canned::SlightLeft, Canned::SlightLeftOntoTheRamp, Canned::SlightRight,
        Canned::SlightRightOntoRamp, Canned::TakeTheInterchange, Canned::TakeTheInterchangeOnTheLeft,
        Canned::TakeTheExit, Canned::TakeTheExitOnTheLeft, Canned::TakeTheExitOnTheRight,
        Canned::TakeTheFerry, Canned::TakeTheInterchangeOnTheRight, Canned::TakeTheRamp,
        Canned::TakeTheTrain, Canned::Then, Canned::TurnLeft, Canned::TurnLeftOntoRamp,
        Canned::TurnRight, Canned::TurnRightOntoTheRamp, Canned::WillArrive,
    ];

    pub fn filename(&self) -> &'static str {
        match self {
            Canned::Arrived => "ARRIVED.wav",
            Canned::ContinueOnTheRamp => "CONTINUE_ON_THE_RAMP.wav",
            Canned::ContinueStraight => "CONTINUE_STRAIGHT.wav",
            Canned::DataLost => "DATA_LOST.wav",
            Canned::DestinationOnLeft => "DESTINATION_ON_LEFT.wav",
            Canned::DestinationOnRight => "DESTINATION_ON_RIGHT.wav",
            Canned::DestinationWillBeOnLeft => "DESTINATION_WILL_BE_ON_LEFT.wav",
            Canned::DestinationWillBeOnRight => "DESTINATION_WILL_BE_ON_RIGHT.wav",
            Canned::EnterTheRoundabout => "ENTER_THE_ROUNDABOUT.wav",
            Canned::ExitTheRoundabout => "EXIT_THE_ROUNDABOUT.wav",
            Canned::GenericContinue => "GENERIC_CONTINUE.wav",
            Canned::GpsLost => "GPS_LOST.wav",
            Canned::HeadEast => "HEAD_EAST.wav",
            Canned::HeadNorth => "HEAD_NORTH.wav",
            Canned::HeadNortheast => "HEAD_NORTHEAST.wav",
            Canned::HeadNorthwest => "HEAD_NORTHWEST.wav",
            Canned::HeadSouth => "HEAD_SOUTH.wav",
            Canned::HeadSoutheast => "HEAD_SOUTHEAST.wav",
            Canned::HeadSouthwest => "HEAD_SOUTHWEST.wav",
            Canned::HeadWest => "HEAD_WEST.wav",
            Canned::In1000Feet => "IN_1000_FEET.wav",
            Canned::In100Feet => "IN_100_FEET.wav",
            Canned::In100Meters => "IN_100_METERS.wav",
            Canned::In100Yards => "IN_100_YARDS.wav",
            Canned::In150Feet => "IN_150_FEET.wav",
            Canned::In150Meters => "IN_150_METERS.wav",
            Canned::In150Yards => "IN_150_YARDS.wav",
            Canned::In1AndAHalfKilometers => "IN_1_AND_A_HALF_KILOMETERS.wav",
            Canned::In1AndAHalfMiles => "IN_1_AND_A_HALF_MILES.wav",
            Canned::In1Kilometer => "IN_1_KILOMETER.wav",
            Canned::In1Mile => "IN_1_MILE.wav",
            Canned::In200Feet => "IN_200_FEET.wav",
            Canned::In200Meters => "IN_200_METERS.wav",
            Canned::In200Yards => "IN_200_YARDS.wav",
            Canned::In2Kilometers => "IN_2_KILOMETERS.wav",
            Canned::In2Miles => "IN_2_MILES.wav",
            Canned::In300Feet => "IN_300_FEET.wav",
            Canned::In300Meters => "IN_300_METERS.wav",
            Canned::In300Yards => "IN_300_YARDS.wav",
            Canned::In3Kilometers => "IN_3_KILOMETERS.wav",
            Canned::In3Miles => "IN_3_MILES.wav",
            Canned::In400Feet => "IN_400_FEET.wav",
            Canned::In400Meters => "IN_400_METERS.wav",
            Canned::In400Yards => "IN_400_YARDS.wav",
            Canned::In500Feet => "IN_500_FEET.wav",
            Canned::In500Meters => "IN_500_METERS.wav",
            Canned::In50Feet => "IN_50_FEET.wav",
            Canned::In50Meters => "IN_50_METERS.wav",
            Canned::In50Yards => "IN_50_YARDS.wav",
            Canned::In600Feet => "IN_600_FEET.wav",
            Canned::In600Meters => "IN_600_METERS.wav",
            Canned::In800Feet => "IN_800_FEET.wav",
            Canned::In800Meters => "IN_800_METERS.wav",
            Canned::InAHalfMile => "IN_A_HALF_MILE.wav",
            Canned::InAQuarterMile => "IN_A_QUARTER_MILE.wav",
            Canned::InThreeQuartersOfAMile => "IN_THREE_QUARTERS_OF_A_MILE.wav",
            Canned::KeepLeftAtTheFork => "KEEP_LEFT_AT_THE_FORK.wav",
            Canned::KeepRightAtTheFork => "KEEP_RIGHT_AT_THE_FORK.wav",
            Canned::MakeAUturn => "MAKE_A_UTURN.wav",
            Canned::NavigationResumed => "NAVIGATION_RESUMED.wav",
            Canned::PleaseDescribeProblem => "PLEASE_DESCRIBE_PROBLEM.wav",
            Canned::Roundabout1stExit => "ROUNDABOUT_1ST_EXIT.wav",
            Canned::RoundaboutExitIntoTheRamp => "ROUNDABOUT_EXIT_INTO_THE_RAMP.wav",
            Canned::RoundaboutTake2ndExit => "ROUNDABOUT_TAKE_2ND_EXIT.wav",
            Canned::RoundaboutTake3rdExit => "ROUNDABOUT_TAKE_3RD_EXIT.wav",
            Canned::RoundaboutTake4thExit => "ROUNDABOUT_TAKE_4TH_EXIT.wav",
            Canned::RoundaboutTake5thExit => "ROUNDABOUT_TAKE_5TH_EXIT.wav",
            Canned::SharpLeft => "SHARP_LEFT.wav",
            Canned::SharpRight => "SHARP_RIGHT.wav",
            Canned::SlightLeft => "SLIGHT_LEFT.wav",
            Canned::SlightLeftOntoTheRamp => "SLIGHT_LEFT_ONTO_THE_RAMP.wav",
            Canned::SlightRight => "SLIGHT_RIGHT.wav",
            Canned::SlightRightOntoRamp => "SLIGHT_RIGHT_ONTO_RAMP.wav",
            Canned::TakeTheInterchange => "TAKE_THE_INTERCHANGE.wav",
            Canned::TakeTheInterchangeOnTheLeft => "TAKE_THE_INTERCHANGE_ON_THE_LEFT.wav",
            Canned::TakeTheExit => "TAKE_THE_EXIT.wav",
            Canned::TakeTheExitOnTheLeft => "TAKE_THE_EXIT_ON_THE_LEFT.wav",
            Canned::TakeTheExitOnTheRight => "TAKE_THE_EXIT_ON_THE_RIGHT.wav",
            Canned::TakeTheFerry => "TAKE_THE_FERRY.wav",
            Canned::TakeTheInterchangeOnTheRight => "TAKE_THE_INTERCHANGE_ON_THE_RIGHT.wav",
            Canned::TakeTheRamp => "TAKE_THE_RAMP.wav",
            Canned::TakeTheTrain => "TAKE_THE_TRAIN.wav",
            Canned::Then => "THEN.wav",
            Canned::TurnLeft => "TURN_LEFT.wav",
            Canned::TurnLeftOntoRamp => "TURN_LEFT_ONTO_RAMP.wav",
            Canned::TurnRight => "TURN_RIGHT.wav",
            Canned::TurnRightOntoTheRamp => "TURN_RIGHT_ONTO_THE_RAMP.wav",
            Canned::WillArrive => "WILL_ARRIVE.wav",
        }
    }
}

const MESSAGES_PLIST: &[u8] = include_bytes!("messages.plist");
const MESSAGES_XML: &[u8] = include_bytes!("messages.xml");

pub fn build_canned_message(map: HashMap<Canned, bytes::Bytes>) -> Result<bytes::Bytes, zip::result::ZipError> {
    use std::io::{Cursor, Write};
    use zip::{write::SimpleFileOptions, ZipWriter};

    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    for (canned, data) in map {
        zip.start_file(canned.filename(), options)?;
        zip.write_all(&data)?;
    }

    zip.start_file("messages.plist", options)?;
    zip.write_all(MESSAGES_PLIST)?;

    zip.start_file("messages.xml", options)?;
    zip.write_all(MESSAGES_XML)?;

    zip.finish()?;
    Ok(bytes::Bytes::from(cursor.into_inner()))
}
